---
   - name: Create the ranger database
     become: true
     mysql_db:
      name: ranger
      state: present
      login_password: "{{ mariadb_root_password }}"

   - name: Create the rangeradmin user and setting privileges
     become: true
     mysql_user:
       login_password: "{{ mariadb_root_password }}"
       name: rangeradmin
       password: rangeradmin
       priv: '*.*:ALL,GRANT'
       host: "{{ item }}"
       state: present
     with_items:
       - "localhost"
       - "{{ ansible_fqdn }}"
       - "%"

   - name: Create the ranger_audit database
     become: true
     mysql_db:
      name: ranger_audit
      state: present
      login_password: "{{ mariadb_root_password }}"

   - name: Create the rangerlogger user and setting privileges
     become: true
     mysql_user:
       login_password: "{{ mariadb_root_password }}"
       name: rangerlogger
       password: rangerlogger
       priv: '*.*:ALL,GRANT'
       host: "{{ item }}"
       state: present
     with_items:
       - "localhost"
       - "{{ ansible_fqdn }}"
       - "%"
